/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SearchButton: typeof import('./src/components/SearchButton.vue')['default']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    WeatherAnimate: typeof import('./src/components/WeatherAnimate.vue')['default']
    WeatherDetails: typeof import('./src/components/WeatherDetails.vue')['default']
    WeatherInfo: typeof import('./src/components/WeatherInfo.vue')['default']
  }
}
